# Generated by Django 3.0.8 on 2020-12-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201205_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='Anonymous', max_length=50),
        ),
    ]
